### ISSUE TITLE
Opening the mobile menu moves Juju logo

### ISSUE THREAD

**Issue by clagom** [canonical-web-and-design/juju.is#224] opened 2021-04-30 16:32 UTC
See image below. On mobile, open the "menu" item and see the Juju logo moves below
![image](https://user-images.githubusercontent.com/1953388/116725566-f5193780-a9d9-11eb-8d63-b00c1dbf3cf4.jpeg)

**Comment by anthonydillon** [comment] 2021-05-03 08:44
Duplicate of #217

**Closed by anthonydillon** 2021-05-03 08:44 UTC
